Agrega solución alternativa a Ovejas
ComiteMexicanoDeInformatica/OMI-Archive pull request #12
Opened 2020-10-14 04:49 UTC by gabrc52

Esta pull request agrega una solución alternativa al problema Ovejas, que no usa BFS.

2020-10-15 19:13 UTC, frcepeda requested changes
Falta hacer lint y agregar la solución a `tests.json`.

2020-10-15 19:57 UTC, gabrc52 commented
Ok

2020-10-15 20:35 UTC, gabrc52 commented
Listo

2020-10-15 21:36 UTC, frcepeda commented
Creo que no corriste bien el linter :c

Pero sí ya pasaron los tests esta vez 👍

2020-10-15 22:06 UTC, gabrc52 commented
Este es el commit del linter https://github.com/ComiteMexicanoDeInformatica/OMI-Archive/pull/12/commits/d927ad93ca39be5e7db459683938c3ae766d24e7

Qué faltó?

2020-10-16 03:40 UTC, frcepeda commented
Ahh, ya veo, está fallando porque esto viene desde un fork. Ya te di permiso de escritura en este repo. Puedes rehacer tu PR en un branch de aquí y no del fork?

2020-10-16 03:46 UTC, closed without merging