problems.json y carpetas
ComiteMexicanoDeInformatica/OMI-Archive pull request #13
Opened 2020-10-15 16:35 UTC by Janque

Ordené los problemas por día y agregue el problems.json

2020-10-15 19:12 UTC, frcepeda requested changes
No entendí qué pasó aquí: parece que solamente borraste muchos archivos.

2020-10-15 19:26 UTC, Janque commented
> No entendí qué pasó aquí: parece que solamente borraste muchos archivos.

Es que se movieron todos a diferentes paths porque de "/problema" se pasaron a /omi/dia-n/problema

2020-10-15 21:34 UTC, frcepeda commented
Pero entonces tienes que hacer `git add` a ese nuevo path, porque si no lo único que pasó es que commiteaste que se borraron y no que se movieron.

2020-10-15 21:45 UTC, Janque commented
> Pero entonces tienes que hacer `git add` a ese nuevo path, porque si no lo único que pasó es que commiteaste que se borraron y no que se movieron.

le puse "commit -a" no asi se añade todo?, ya hice un nuevo commit ahora hago el pr

2020-10-16 00:41 UTC, frcepeda requested changes
Va mejorando.

El problems.json es el que va en la raíz: no tiene ningún efecto tener algo bajo `2017`. (El que está en `2020` es error mío...) Hay que poner lo que pusiste en `2017/problems.json` en el `problems.json` de la raíz.

Este pull request qué se supone que es la meta? Si es dejar los problemas listos en el CI, te falta agregar el `settings.json` de todos los problemas y sus tests correspondientes. (Aunque puedes poner tests dummy que siempre pasen, porque _en teoría_ los casos están bien.)

2020-10-16 01:58 UTC, andreasantillana commented
Otra cosa que podrías hacer @Janque es irte de problema en problema para que no sean tantísimos cambios
Aquí puedes ver uno de un solo problema que ya está casi listo.
https://github.com/ComiteMexicanoDeInformatica/OMI-Archive/pull/14

2020-10-16 18:25 UTC, Janque commented
> Este pull request qué se supone que es la meta? Si es dejar los problemas listos en el CI, te falta agregar el `settings.json` de todos los problemas y sus tests correspondientes. (Aunque puedes poner tests dummy que siempre pasen, porque _en teoría_ los casos están bien.)

Es que pensé que sería mejor primero ponerlos ordenarlos y después darle formato a cada uno

2020-10-16 22:16 UTC, Juanito98 commented
Este pr solo se mete con 2017 verdad?

2020-10-16 22:17 UTC, Janque commented
> Este pr solo se mete con 2017 verdad?
> Para irle moviendo al 2018

si

2020-10-16 22:22 UTC, frcepeda approved these changes

2020-10-16 22:25 UTC, merged