Add OMI/PS 2021 problem statements, cases and solutions
ComiteMexicanoDeInformatica/OMI-Archive pull request #37
Opened 2021-09-11 17:48 UTC by Apocryphon-X

2021-09-11 20:52 UTC, frcepeda requested changes
Falta agregar todos los problemas al `problems.json` y que pasen los tests

2021-09-12 02:59 UTC, Apocryphon-X commented
> Falta agregar todos los problemas al `problems.json` y que pasen los tests

Ya quedó

2021-09-12 03:43 UTC, frcepeda requested changes

2021-09-12 03:43 UTC, frcepeda commented on 2021/omi/OMI-2021-Fichas/settings.json
> +    "visibility": "private",
```suggestion
    "visibility": "public",
```
Última cosa que falta es que como ahora los problemas son públicos hay que actualizar los `settings.json`.

2021-09-13 00:13 UTC, frcepeda approved these changes

2021-09-13 00:56 UTC, merged